config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :posts, only: %i[index create show] do
    resources :comments, only: :create
    resources :likes, only: :create
  end

  resources :users, only: [:show]

  resources :likes, only: :destroy
  resources :profiles, only: %i[show]
  resources :chatrooms, only: %i[show index create] do
    resources :messages, only: :create
    get 'messages', on: :member, to: 'chatrooms#show_messages'
  end
end

app/views/shared/_footer.html.erb
<footer class = "footer secondary-text">
  <% if user_signed_in? %>
    Connecting Moosician's globally.
  <% else %>
    welcome to Moosicain!
  <% end %>
</footer>

app/views/shared/_message.html.erb
<div class="py-3">
  <div class="message-card d-flex flex-column p-4 align-items-center">
    <div class="pb-2 comment-card d-flex justify-content-center">
      <h3 class="name-username">Messages</h3>
    </div>
    <% unless @last_messages.empty? %>
      <% @last_messages.each_with_index do |message, index| %>
        <%= link_to chatroom_path(Chatroom.find(message.chatroom_id)), class: "w-100" do %>
          <div class="d-flex align-items-center py-2 <%= puts "comment-card" unless index == @last_messages.length %>">
            <%= cl_image_tag message.user.photo.key %>
            <div class="flex-grow-1 ms-3">
              <div class="details">
                <div class="name"><%= message.user.first_name %> <%= message.user.last_name %></div>
                <div class="content"><%= message.content %></div>
                <div class="date"><i><%= message.created_at.strftime("sent at %I:%M%p - %m/%d/%Y") %></i></div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="secondary-text">No new messages</p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-lewagon" >
  <div class="container-fluid">
  <div class="row w-100">
    <div class="col-3 d-flex justify-content-start align-items-center">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="navbar-dropdown-btn" type="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-bars fa-2xl"></i></button>
          <ul class="dropdown-menu navbar-dropdown-menu">
            <%= link_to "Feed", root_path, class: "dropdown-item" %>
            <% if current_user.profile %>
              <%= link_to "My profile", profile_path(current_user.profile.id), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
          </ul>
        </div>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "navbar-dropdown-btn" %>
        <% end %>
    </div>
      <div class="col-6 d-flex justify-content-center align-items-center">
        <%= link_to root_path do %>
        <h1 style="font-family: 'Bebas Neue', sans-serif;" class="m-0">Moosician</h1>
        <% end %>
      </div>
      <div class="col-3 d-flex justify-content-end align-items-center" >
         <%= form_with url: posts_path, method: :get, html: {class: "d-flex w-100", data: {search_global_target: "form"}} do %>
            <%= text_field_tag :query,
                  params[:query],
                  data: {
                    search_global_target: "input",
                    action: "keyup->search-global#update"},
                  class: "form-control navbar-search",
                  placeholder: "Search"
              %>
            <%= button_tag type: "submit", class: "btn navbar-search-btn" do %>
              <i class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_profile_horizontal.html.erb
<div class="py-3">
  <div class="profile-card">
    <div class="d-flex p-3">
      <%= cl_image_tag user.photo.key, class: "avatar-large" %>
      <div class="d-flex flex-column w-100 ms-3 justify-content-between">
        <div class="flex-column flex-grow-1 justify-content-between">
          <div class="d-flex align-items-center mb-3">
            <h3 class="name-username"><%= user.first_name %> <%= user.last_name %></h3>
            <p class="secondary-text ps-1 name-username">@<%= user.username %></p>
          </div>
          <p><%= user.bio %></p>
          <p>Joined on <%= user.created_at.strftime("#{current_user.created_at.day.ordinalize} of %b, %Y") %></p>
        </div>
        <div class="d-flex justify-content-end">
        <% chatroom = Chatroom.find_by(user_1: user, user_2: current_user) || chatroom = Chatroom.find_by(user_2: user, user_1: current_user)   %>
          <% if chatroom.nil? %>
            <%= button_to chatrooms_path(receiver: user), class: "remove-btn-class" do %>
              <i class=" icon fa-2xl fa-regular fa-envelope"></i>
            <% end %>
          <% else %>
            <%= link_to chatroom_path(chatroom), class: "remove-btn-class" do %>
              <i class=" icon fa-2xl fa-regular fa-envelope"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_profile_vertical.html.erb
    <div class="index-card">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "avatar-large mb-3" %>
      <% end %>
      <h3 class="name-username"><%= current_user.first_name %>
      <%= current_user.last_name %></h3>
      <p class="secondary-text">@<%= current_user.username %></p>
      <p><%= current_user.bio %></p>

      <% if current_user.profile %>
       <%= link_to "My profile", profile_path(current_user.profile.id), class: "moosician-btn", style: "margin-bottom: 16px;" %>
      <%end %>
      <p class= "secondary-text">Joined on <%= current_user.created_at.strftime("#{current_user.created_at.day.ordinalize} of %b, %Y") %></p>
    </div>