config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :posts, only: %i[index create show] do
    resources :comments, only: :create
    resources :likes, only: :create
  end

  resources :users, only: [:show]

  resources :likes, only: :destroy
  resources :profiles, only: %i[show]
  resources :chatrooms, only: %i[show index create] do
    resources :messages, only: :create
    get 'messages', on: :member, to: 'chatrooms#show_messages'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  has_one_attached :audio_data

  # validates :title, presence: true
  validates :description, presence: true

  VALID_URL_REGEX = /\A(?:(?:http|https):\/\/)?
                    (?:[\wZ]+(?::[\wZ]+)?@)?
                    (?:[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6})
                    (?:\:[0-9]{1,5})?
                    (?:\/\S*)?\z/x
 validates_format_of :music_url, with: VALID_URL_REGEX, allow_blank: true, message: 'is not a valid URL',if: -> { self.audio_data.blank? }


  # validates :category, inclusion: { in: ["rock", "jazz", "blues", "hiphop", "rap"] }

  attr_accessor :attachment_url

  def liked_by_user?(user)
    self.likes.find_by(user: user).present?
  end

end

#test

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = policy_scope(Post)
    @post = Post.new
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR description ILIKE :query OR username ILIKE :query"
      @posts = Post.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    else
      @posts = policy_scope(Post)
    end
    @comment = Comment.new
    get_last_messages
    respond_to do |format|
      format.html
      format.text { render partial: "posts/list", locals: { posts: @posts }, formats: [:html] }
    end


  end

  def show
    @post = Post.find(params[:id])
    authorize @post
  end

  def create
    #  result = Cloudinary::Uploader.upload(params[:post][:attachment])
    @post = Post.new(post_params)
    #  @post.attachment_url = result['secure_url']
    @post.user = current_user
    get_last_messages
    if @post.save
      @posts = policy_scope(Post)
      @comment = Comment.new
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
    else
      @comment = Comment.new
      @received_messages = current_user.chatrooms.map { |chatroom| chatroom.messages.where.not(user: current_user) }
      @posts = policy_scope(Post)
      render :index, status: :unprocessable_entity
    end
    authorize @post
  end

  private

  def post_params
    params.require(:post).permit(:description, :audio_data, :music_url, :embed_url)
  end

  def get_last_messages
    @chatrooms = policy_scope(Chatroom)
    @last_messages = []
    @chatrooms.each do |chatroom|
      @last_messages << chatroom.messages.last unless chatroom.messages.last == nil || chatroom.messages.last.user == current_user
    end
  end

end

app/views/posts/_list.html.erb
<%# some sort of an iteration %>
<%# you take an array of Post instances (@posts) %>
<%# and you create a _post.html.erb for each of them %>
<div data-search-global-target="list">
  <% unless params[:query].blank?%>
    <div class="d-flex justify-content-end pt-2">
      <p class="h3 name-username">
        <%=pluralize posts.count , "result"  %> for <code> <%=params[:query] %></code>
      </p>
    </div>
  <% end %>
  <div class="posts">
    <%posts.each do |post| %>
      <%= render "post" ,post: post%>
    <% end  %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="my-4" data-controller="comments">
  <div class="index-card" data-comments-target="indexCard">
    <div class = "w-100">
      <%= link_to "", post_path(post.id) %>
      <% if current_user.profile %>
        <%= link_to profile_path(post.user.profile) do %>
          <div class="d-flex add-border">
            <%= cl_image_tag post.user.photo.key, class: "avatar me-2" %>
            <div>
              <div>
                <p class="name-username pt-2">
                  <b><%= post.user.first_name %>
                    <%= post.user.last_name %></b>
                  @<%= post.user.username %>
                </p>
              </div>
              <p class="name-username secondary-text pb-2" style="font-size: 14px;"><i><%= post.created_at.strftime("created at %I:%M%p on %m/%d/%Y") %></i>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
      <h1 class="name-username my-3 ms-1"><%= post.description %></h1>
      <% if post.embed_url.present? %>
        <div class="video-container">
          <%= raw post.embed_url %>
        </div>
      <% end %>


      <div class="w-100 d-flex justify-content-end mb-2">
        <% if post.music_url.present? %>
          <%= link_to post.music_url, target: "_blank" do %>
            <div class="d-flex align-items-center">
              <p class="pe-2 name-username secondary-text" style="font-size: 14px;">Open link </p>
              <i class=" fa-solid fa-arrow-up-right-from-square fa-xs secondary-text"></i>
            </div>
          <% end %>
        <% end %>
      </div>
      <% if post.audio_data.attached? %>
        <%= audio_tag post.audio_data.url, controls:true %>
      <% end %>
      <%= turbo_frame_tag dom_id(post, :like) do %>
        <div class="d-flex align-items-center justify-content-between">
          <div class ="d-flex align-items-center">
            <h5 class="me-1 mb-0 text-color"><%= post.likes.length %></h5>

            <% if post.liked_by_user?(current_user) %>
              <%= link_to like_path(post.likes.find_by(user: current_user)), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart fa-sharp icon fa-xl me-2"></i>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(post), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart fa-sharp icon fa-xl me-2"></i>
              <% end %>
            <% end %>
            <%# <% end MAYBE END OF TURBOFRAME%>
            <h5 class="me-1 mb-0 text-color"><%= post.comments.length %></h5>
            <i class="fa-solid fa-comment fa-sharp icon fa-xl me-1" data-action="click->comments#display"></i>
          </div>
          <div class="dropdown">
            <a class="btn dropdown-toggle" style="padding: 0px;" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-share icon fa-xl"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a type="button" class="shareButton mx-2" tabindex="0" href="https://twitter.com/intent/tweet?text=<%= url_encode("Check out this awesome post: #{post.description} - #{post_url(post)}") %>"  target="_blank" title="Share on Twitter" arial-label="Share on Twitter">
                <i class="fab fa-twitter icon" style="font-size:20px;"></i></a>
              <a type="button" class="shareButton mx-2" tabindex="0" href="https://www.facebook.com/sharer/sharer.php?u=<%= url_encode(post_url(post)) %>" target="_blank" title="Share on Facebook" arial-label="Share on Facebook">
                <i class="fab fa-facebook-f icon" style="font-size:20px;"></i></a>
              <a type="button" class="shareButton mx-2" tabindex="0" href="https://www.tumblr.com/widgets/share?title=<%= url_encode(post.description) %>&url=<%= url_encode(post_url(post)) %>" target="_blank" title="Share on Tumblr" arial-label="Share on Tumblr">
                <i class="fab fa-tumblr icon" style="font-size:20px;"></i></a>
              <a type="button" class="shareButton mx-2" tabindex="0" href="https://api.whatsapp.com/send?text=<%= url_encode("Check out this awesome post: #{post.description} - #{post_url(post)}") %>" target="_blank" title="Share on WhatsApp" aria-label="Share on WhatsApp">
                <i class="fab fa-whatsapp icon" style="font-size:20px;"></i></a>
              <a type="button" class="shareButton mx-2" tabindex="0" href="mailto:?subject=<%= url_encode("Check out this awesome post: #{post.description}") %>&body=<%= url_encode("Check out this awesome post: #{post.description} - #{post_url(post)}") %>" target="_blank" title="Share via email" arial-label="Share via email">
                <i class="fa fa-envelope icon" style="font-size:20px;"></i></a>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="comment-container d-none" data-comments-target="commentsContainer">
    <%= render post.comments %>
    <div class="w-100">
      <%= render "comments/form", post: post, comment: @comment %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mt-2 py-3 px-4">
    <%= render "shared/profile_vertical" %>
    </div>
    <div class="col-6 mt-2 px-4">

      <%= form_with(model: @post, url: posts_path, remote: true, html: { multipart: true, class: "form-post" }) do |form| %>
        <div class="d-flex flex-column align-items-end w-100 mt-3 index-card">
          <% if @post.errors.any? %>
            <% @post.errors.full_messages.each do |message| %>
              <p style="color: red"><%= message %></p>
            <% end %>
          <% end %>
          <%= form.text_area :description, class: "form-control new-post-textfield mb-2", placeholder: "Whats on your mind Moosician" %>
          <div class="input-group mb-3 d-flex align-items-center ">
            <div class="input-group-prepend  p-2">
              <span ><i class="fa-solid fa-link icon"></i></span>
            </div>
            <%= form.text_field :embed_url, class: "form-control new-post-textfield-secondary border-0",'data-toggle': "tooltip", 'data-placement': "left" ,:title => "Paste the link to an embedded song, e.g., a Spotify or YouTube embed link. example: <iframe src='https://www.example.com'></iframe>", placeholder: "Add an embedded music link..." %>
          </div>

          <div class="input-group mb-3 d-flex align-items-center ">
          <div class="input-group-prepend p-2">
            <span ><i class="fa-solid fa-link icon"></i></span>
          </div>
          <%= form.text_field :music_url, class: "form-control new-post-textfield-secondary border-0",'data-toggle': "tooltip", 'data-placement': "left" ,:title => "Add a direct URL to the music file or to a music-sharing platform. Examples: https://example.com/song.mp3, https://youtube.com/watch?v=example", placeholder: "Add a url link..." %>

          </div>
          <%# form.text_area :description, class: "form-control", placeholder: "What's happening?" %>
          <%= form.file_field :audio_data, id: "fileInput", class: "input-file" %>
          <div class="icon-container">
            <label class="control-label" for="fileInput">
              <i class="fa-solid fa-file-audio fa-xl icon"></i>
            </label>
            <button type="submit" class="remove-btn-style">
              <i class="fa-solid fa-paper-plane fa-xl icon" id="sendIcon"></i>
            </button>
          </div>
        </div>
      <% end %>
      <div data-search-global-target="list">
        <%= render @posts %>
      </div>
      <%# <% @posts.each do |post| %>
        <%# <%= render "posts/post", post: post %>
        <%# <% end %>
      </div>
      <div class="col-3 mt-2 px-4">
        <%= render "shared/message" %>
      </div>
    </div>
  </div>